// Seed data — Lyon terrain. Fictional but realistic prospects across the
// four EAGLEYE verticals: restaurants, pubs, ambulances, artisans.
import type {
  Activity,
  Campaign,
  Competitor,
  Meeting,
  NurtureSequence,
  Prospect,
} from "./types";
import { daysAgo, daysAhead } from "./utils";

export const seedProspects: Prospect[] = [
  {
    id: "p-bouchon",
    name: "Marc Perrin",
    company: "Le Bouchon des Canuts",
    sector: "restaurant",
    city: "Lyon 4e — Croix-Rousse",
    phone: "04 78 12 34 56",
    email: "contact@bouchondescanuts.fr",
    stage: "redzone",
    trust: 82,
    auditScore: 90,
    conviction: 9,
    monthlyValue: 290,
    setupValue: 1800,
    probability: 78,
    ignoranceTax: 2400,
    croyances: { produit: 10, soutien: 10, pourLui: 7 },
    obstacles: [
      { id: "o1", label: "« Les clients viennent par bouche-à-oreille »", blameLayer: "circonstances", resolved: true, note: "Audit : 62 % des recherches « bouchon croix-rousse » partent chez le concurrent." },
    ],
    objections: [
      { id: "j1", label: "« C'est trop cher pour un resto comme le mien »", type: "argent", croyance: 3, status: "ouverte", counter: "Taxe d'Ignorance 2 400 €/mois vs 290 €/mois. Le calcul sur SON téléphone." },
    ],
    events: [
      { id: "e1", date: daysAgo(21), kind: "visite", summary: "Passage 15h, heure creuse. Marc sceptique mais curieux.", nextStep: { date: daysAgo(14), action: "Revenir avec audit chiffré" } },
      { id: "e2", date: daysAgo(14), kind: "meeting", summary: "Audit sur place : 40+ appels ratés/mois, fiche Google à l'abandon.", nextStep: { date: daysAgo(7), action: "Démo mobile maquette" } },
      { id: "e3", date: daysAgo(7), kind: "demo", summary: "Démo mobile avec SA devanture en photo. Émotion visible — il a montré au chef.", nextStep: { date: daysAgo(2), action: "Présenter l'offre" } },
      { id: "e4", date: daysAgo(2), kind: "offre", summary: "Offre : 1 800 € setup + 290 €/mois. Objection prix immédiate.", nextStep: { date: daysAhead(1), action: "Closing — recadrage Taxe d'Ignorance" } },
    ],
    demoShownBeforePrice: true,
    nextStep: { date: daysAhead(1), action: "Closing — recadrage Taxe d'Ignorance avec calcul sur son téléphone" },
    tags: ["chaud", "croix-rousse"],
    attachments: [
      { id: "a1", name: "audit-bouchon-canuts.pdf", kind: "audit", size: 245000, addedAt: daysAgo(14) },
      { id: "a2", name: "maquette-mobile-v2.png", kind: "maquette", size: 890000, addedAt: daysAgo(7) },
    ],
    notes: "Fait 90 couverts le week-end, 15 en semaine. Le mardi soir est mort. Femme tient la caisse — l'inclure dans la boucle.",
    createdAt: daysAgo(25),
    updatedAt: daysAgo(2),
  },
  {
    id: "p-smoking-dog",
    name: "Aurélie Vasseur",
    company: "The Smoking Dog Pub",
    sector: "pub",
    city: "Lyon 5e — Vieux Lyon",
    phone: "04 78 98 76 54",
    email: "aurelie@smokingdog.fr",
    stage: "demo",
    trust: 65,
    auditScore: 75,
    conviction: 8,
    monthlyValue: 240,
    setupValue: 1400,
    probability: 50,
    ignoranceTax: 1800,
    croyances: { produit: 8, soutien: 9, pourLui: 6 },
    obstacles: [
      { id: "o1", label: "« Mon barman gère l'Instagram, ça suffit »", blameLayer: "autres", resolved: true, note: "Insta ≠ réservation. Zéro conversion mesurée." },
      { id: "o2", label: "« Les soirées quiz se remplissent toutes seules »", blameLayer: "circonstances", resolved: false },
    ],
    objections: [],
    events: [
      { id: "e1", date: daysAgo(12), kind: "visite", summary: "Contact au comptoir un mardi creux. 8 clients dans la salle.", nextStep: { date: daysAgo(8), action: "Audit express" } },
      { id: "e2", date: daysAgo(8), kind: "meeting", summary: "Audit : mardi/mercredi = 20 % de remplissage. Événements annoncés à la craie.", nextStep: { date: daysAhead(2), action: "Démo mobile agenda IA" } },
    ],
    demoShownBeforePrice: false,
    nextStep: { date: daysAhead(2), action: "Démo mobile : agenda événements + relances WhatsApp automatiques" },
    tags: ["vieux-lyon", "événementiel"],
    attachments: [],
    notes: "Anglophone, clientèle expat + étudiants. Très sensible à l'esthétique — la démo doit être léchée.",
    createdAt: daysAgo(14),
    updatedAt: daysAgo(8),
  },
  {
    id: "p-ambulances-rhone",
    name: "Karim Benali",
    company: "Ambulances Rhône Assistance",
    sector: "ambulance",
    city: "Villeurbanne",
    phone: "04 72 11 22 33",
    email: "k.benali@ambulances-rhone.fr",
    stage: "audit",
    trust: 55,
    auditScore: 40,
    conviction: 8,
    monthlyValue: 390,
    setupValue: 2400,
    probability: 30,
    ignoranceTax: 3600,
    croyances: { produit: 7, soutien: 8, pourLui: 5 },
    obstacles: [
      { id: "o1", label: "« Le standard gère, on a toujours fait comme ça »", blameLayer: "circonstances", resolved: false },
      { id: "o2", label: "« Mon frère co-gérant doit valider »", blameLayer: "autres", resolved: false },
    ],
    objections: [],
    events: [
      { id: "e1", date: daysAgo(10), kind: "appel", summary: "Appel entrant suite reco du Bouchon des Canuts (même expert-comptable).", nextStep: { date: daysAgo(4), action: "RDV audit au dépôt" } },
      { id: "e2", date: daysAgo(4), kind: "meeting", summary: "Visite dépôt. Standard saturé 8h-10h, demandes de nuit perdues.", nextStep: { date: daysAhead(3), action: "Finaliser audit chiffré + inviter le frère" } },
    ],
    demoShownBeforePrice: false,
    nextStep: { date: daysAhead(3), action: "Audit chiffré + démo à deux avec le frère co-gérant" },
    tags: ["referral", "b2b"],
    attachments: [{ id: "a1", name: "notes-depot.pdf", kind: "audit", size: 120000, addedAt: daysAgo(4) }],
    notes: "2 co-gérants — TOUJOURS les deux frères présents pour la démo. Karim est le champion interne.",
    createdAt: daysAgo(10),
    updatedAt: daysAgo(4),
  },
  {
    id: "p-menuiserie",
    name: "Sylvie Charbonnier",
    company: "Menuiserie Charbonnier & Fils",
    sector: "artisan",
    city: "Caluire-et-Cuire",
    phone: "06 45 67 89 01",
    email: "contact@menuiserie-charbonnier.fr",
    stage: "signe",
    trust: 95,
    auditScore: 100,
    conviction: 10,
    monthlyValue: 190,
    setupValue: 1200,
    probability: 100,
    ignoranceTax: 1500,
    croyances: { produit: 10, soutien: 10, pourLui: 10 },
    obstacles: [
      { id: "o1", label: "« J'ai déjà payé pour un site qui n'a rien donné »", blameLayer: "soi", resolved: true, note: "Ancien site 2014, jamais référencé. Preuve : artisan plombier Caluire équipé, +9 devis/mois." },
    ],
    objections: [
      { id: "j1", label: "« Je vais réfléchir »", type: "temps", croyance: 3, status: "traitee", counter: "Isolé la vraie peur (re-payer pour rien) → garantie résultat conditionnelle." },
    ],
    events: [
      { id: "e1", date: daysAgo(40), kind: "visite", summary: "Contact atelier via marché des artisans.", nextStep: { date: daysAgo(33), action: "Audit" } },
      { id: "e2", date: daysAgo(33), kind: "meeting", summary: "Audit : 12 appels manqués/semaine pendant les chantiers." },
      { id: "e3", date: daysAgo(26), kind: "demo", summary: "Démo mobile formulaire devis intelligent. Son fils a dit « enfin ! »." },
      { id: "e4", date: daysAgo(20), kind: "offre", summary: "Offre acceptée après traitement « je vais réfléchir »." },
      { id: "e5", date: daysAgo(18), kind: "stage", summary: "SIGNÉ ✓ — 1 200 € setup + 190 €/mois. Conviction 10/10." },
    ],
    demoShownBeforePrice: true,
    nextStep: { date: daysAhead(5), action: "Point onboarding + demander 2 recommandations d'artisans" },
    tags: ["signé", "referral-source"],
    attachments: [{ id: "a1", name: "proposition-signee.pdf", kind: "proposition", size: 310000, addedAt: daysAgo(18) }],
    notes: "Cliente ambassadrice. Le fils (Thomas) gère le téléphone — le former sur l'overlay IA.",
    wonAt: daysAgo(18),
    createdAt: daysAgo(40),
    updatedAt: daysAgo(18),
  },
  {
    id: "p-brasserie-part-dieu",
    name: "Olivier Roux",
    company: "Brasserie du Lac",
    sector: "restaurant",
    city: "Lyon 3e — Part-Dieu",
    phone: "04 72 33 44 55",
    stage: "contact",
    trust: 35,
    auditScore: 10,
    conviction: 7,
    monthlyValue: 290,
    setupValue: 1800,
    probability: 15,
    ignoranceTax: 2000,
    croyances: { produit: 5, soutien: 6, pourLui: 3 },
    obstacles: [
      { id: "o1", label: "« Pas le moment, c'est la haute saison »", blameLayer: "circonstances", resolved: false },
      { id: "o2", label: "« Mon neveu s'occupe déjà du site »", blameLayer: "autres", resolved: false },
    ],
    objections: [],
    events: [
      { id: "e1", date: daysAgo(6), kind: "visite", summary: "Premier passage. Poli mais pressé. Deux couches d'oignon posées d'entrée.", nextStep: { date: daysAhead(4), action: "Repasser avec le comparatif site du neveu vs démo" } },
    ],
    demoShownBeforePrice: false,
    nextStep: { date: daysAhead(4), action: "Repasser à 15h avec comparatif : site actuel vs maquette EAGLEYE" },
    tags: ["part-dieu"],
    attachments: [],
    notes: "Terrasse 60 places sous-exploitée. Le site du neveu : dernière mise à jour il y a 2 ans.",
    createdAt: daysAgo(6),
    updatedAt: daysAgo(6),
  },
  {
    id: "p-taxi-fourviere",
    name: "Nadia Slimani",
    company: "Ambulances Fourvière Santé",
    sector: "ambulance",
    city: "Lyon 9e — Vaise",
    stage: "prospect",
    trust: 10,
    auditScore: 0,
    conviction: 7,
    monthlyValue: 390,
    setupValue: 2400,
    probability: 5,
    ignoranceTax: 3000,
    croyances: { produit: 3, soutien: 3, pourLui: 2 },
    obstacles: [],
    objections: [],
    events: [],
    demoShownBeforePrice: false,
    nextStep: { date: daysAhead(2), action: "Premier contact : appeler avant 8h (avant les tournées)" },
    tags: ["à-contacter"],
    attachments: [],
    notes: "Repérée via annuaire ARS. Flotte de 6 véhicules. Site inexistant.",
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
  },
  {
    id: "p-paddy",
    name: "Sean Murphy",
    company: "Paddy's Corner",
    sector: "pub",
    city: "Lyon 2e — Cordeliers",
    stage: "perdu",
    trust: 40,
    auditScore: 55,
    conviction: 6,
    monthlyValue: 240,
    setupValue: 1400,
    probability: 0,
    ignoranceTax: 1600,
    croyances: { produit: 6, soutien: 4, pourLui: 3 },
    obstacles: [
      { id: "o1", label: "« La conjoncture est mauvaise »", blameLayer: "circonstances", resolved: false },
    ],
    objections: [
      { id: "j1", label: "« Un concurrent me propose moins cher »", type: "concurrent", croyance: 1, status: "bloquante", counter: "Parti chez WebLyon Express à 49 €/mois. Rendez-vous dans 6 mois quand le site low-cost n'aura rien produit." },
    ],
    events: [
      { id: "e1", date: daysAgo(30), kind: "visite", summary: "Bon premier contact." },
      { id: "e2", date: daysAgo(15), kind: "offre", summary: "Offre présentée — AVANT la démo mobile (erreur doctrine)." },
      { id: "e3", date: daysAgo(9), kind: "stage", summary: "Perdu vs WebLyon Express. Cause racine : prix annoncé sans émotion préalable." },
    ],
    demoShownBeforePrice: false,
    nextStep: { date: daysAhead(90), action: "Nurture : reprendre contact quand le site low-cost aura montré ses limites" },
    tags: ["nurture", "leçon"],
    attachments: [],
    notes: "LEÇON : offre présentée sans démo mobile. La doctrine existe pour une raison. Recontact planifié J+90.",
    lostReason: "Concurrent low-cost — offre présentée avant la démo (violation doctrine)",
    createdAt: daysAgo(30),
    updatedAt: daysAgo(9),
  },
  {
    id: "p-boulangerie",
    name: "Étienne Fabre",
    company: "Plomberie Fabre",
    sector: "artisan",
    city: "Lyon 7e — Gerland",
    phone: "06 12 98 76 54",
    stage: "offre",
    trust: 70,
    auditScore: 85,
    conviction: 9,
    monthlyValue: 190,
    setupValue: 1200,
    probability: 65,
    ignoranceTax: 2200,
    croyances: { produit: 9, soutien: 9, pourLui: 8 },
    obstacles: [
      { id: "o1", label: "« Je suis nul avec la technologie »", blameLayer: "soi", resolved: true, note: "« Vous n'avez rien à toucher. Tout arrive par SMS. »" },
    ],
    objections: [],
    events: [
      { id: "e1", date: daysAgo(18), kind: "appel", summary: "Reco de Sylvie Charbonnier (Menuiserie).", nextStep: { date: daysAgo(12), action: "Audit" } },
      { id: "e2", date: daysAgo(12), kind: "meeting", summary: "Audit : 12 appels manqués/semaine sur chantier. Urgences plomberie = or perdu." },
      { id: "e3", date: daysAgo(5), kind: "demo", summary: "Démo mobile : demande d'urgence qualifiée en 40 s. Il a testé lui-même, trois fois." },
      { id: "e4", date: daysAgo(1), kind: "offre", summary: "Offre posée après démo (doctrine respectée). Réponse attendue.", nextStep: { date: daysAhead(1), action: "Appel décision" } },
    ],
    demoShownBeforePrice: true,
    nextStep: { date: daysAhead(1), action: "Appel décision 9h (avant ses chantiers)" },
    tags: ["referral", "chaud"],
    attachments: [{ id: "a1", name: "proposition-fabre.pdf", kind: "proposition", size: 298000, addedAt: daysAgo(1) }],
    notes: "Referral chain : Charbonnier → Fabre. La preuve « pour lui » est déjà faite par Sylvie.",
    createdAt: daysAgo(18),
    updatedAt: daysAgo(1),
  },
];

export const seedCampaigns: Campaign[] = [
  {
    id: "c-restos-hiver",
    name: "Restos Lyon — Remplir les soirs creux",
    sector: "restaurant",
    status: "active",
    steps: [
      { id: "s1", kind: "email", delayDays: 0, subject: "Vos mardis soirs, M. {prenom}", body: "Bonjour {prenom},\n\nJ'ai compté : {concurrents} restaurants dans votre rue prennent des réservations à 23h. Pas vous.\n\nChaque mardi soir vide vous coûte environ {taxe} €. Je passe 10 minutes vous montrer, sur mon téléphone, à quoi ressemblerait {commerce} en ligne — sans engagement, sans prix, juste pour voir.\n\n{closer} — EAGLEYE, Lyon" },
      { id: "s2", kind: "whatsapp", delayDays: 3, subject: "Relance douce", body: "Bonjour {prenom}, c'est {closer} (EAGLEYE Lyon). Je vous ai envoyé un mot sur vos soirées creuses — je passe mardi à 15h dans le quartier, je vous montre 2 minutes ?" },
      { id: "s3", kind: "appel", delayDays: 6, subject: "Appel heure creuse", body: "Appeler entre 14h30 et 17h. Objectif unique : décrocher 20 min d'audit terrain daté. Zéro pitch produit au téléphone." },
    ],
    stats: { sent: 42, opened: 28, replied: 9, booked: 4 },
    createdAt: daysAgo(20),
  },
  {
    id: "c-ambulances",
    name: "Ambulanciers Rhône — Standard 24/7",
    sector: "ambulance",
    status: "active",
    steps: [
      { id: "s1", kind: "email", delayDays: 0, subject: "Les demandes de nuit que vous ne voyez jamais", body: "Bonjour {prenom},\n\nEntre 20h et 7h, votre standard dort. Les demandes de transport programmé, elles, continuent d'arriver — chez ceux qui répondent.\n\nOn équipe des ambulanciers du Rhône avec un standard IA qui qualifie et route 24/7. Audit gratuit de vos flux : 20 minutes au dépôt.\n\n{closer} — EAGLEYE" },
      { id: "s2", kind: "appel", delayDays: 4, subject: "Appel avant tournées", body: "Appeler avant 8h. Mentionner les confrères équipés. Objectif : RDV dépôt daté." },
    ],
    stats: { sent: 18, opened: 12, replied: 5, booked: 2 },
    createdAt: daysAgo(12),
  },
  {
    id: "c-artisans",
    name: "Artisans — Devis pendant le chantier",
    sector: "artisan",
    status: "brouillon",
    steps: [
      { id: "s1", kind: "email", delayDays: 0, subject: "12 appels manqués par semaine", body: "Bonjour {prenom},\n\nUn artisan sur chantier rate en moyenne 12 appels par semaine. Chaque appel raté = un devis chez le concurrent.\n\nNos artisans reçoivent des demandes pré-qualifiées (budget, délai, photos) par SMS, sans décrocher. {preuve}\n\nJe vous montre sur votre téléphone ? 10 minutes, quand vous voulez.\n\n{closer} — EAGLEYE" },
    ],
    stats: { sent: 0, opened: 0, replied: 0, booked: 0 },
    createdAt: daysAgo(5),
  },
];

export const seedMeetings: Meeting[] = [
  { id: "m1", prospectId: "p-bouchon", title: "Closing — Le Bouchon des Canuts", date: daysAhead(1), durationMin: 45, kind: "closing", location: "Sur place — Croix-Rousse", calLink: "https://cal.com/eagleye/closing-bouchon", reminded: true, done: false },
  { id: "m2", prospectId: "p-smoking-dog", title: "Démo mobile — Smoking Dog", date: daysAhead(2), durationMin: 30, kind: "demo", location: "Sur place — Vieux Lyon", calLink: "https://cal.com/eagleye/demo-smokingdog", reminded: false, done: false },
  { id: "m3", prospectId: "p-ambulances-rhone", title: "Audit + démo (les 2 frères)", date: daysAhead(3), durationMin: 60, kind: "audit", location: "Dépôt Villeurbanne", calLink: "https://cal.com/eagleye/audit-rhone", reminded: false, done: false },
  { id: "m4", prospectId: "p-boulangerie", title: "Appel décision — Plomberie Fabre", date: daysAhead(1), durationMin: 15, kind: "closing", location: "Téléphone", reminded: true, done: false },
  { id: "m5", prospectId: "p-menuiserie", title: "Onboarding + referrals — Charbonnier", date: daysAhead(5), durationMin: 45, kind: "suivi", location: "Atelier Caluire", calLink: "https://cal.com/eagleye/onboarding-charbonnier", reminded: false, done: false },
];

export const seedNurture: NurtureSequence[] = [
  {
    id: "n-perdus-90j",
    name: "Perdus — Reconquête 90 jours",
    audience: "Prospects perdus (surtout vs low-cost)",
    active: true,
    steps: [
      { id: "ns1", day: 30, channel: "email", content: "Article utile secteur (zéro vente) : « 3 choses que les meilleurs {secteur}s de Lyon font en ligne »." },
      { id: "ns2", day: 60, channel: "whatsapp", content: "Message personnel : une preuve fraîche même secteur (« on vient d'équiper X, +N clients/mois »)." },
      { id: "ns3", day: 90, channel: "appel", content: "Appel direct : « Où en êtes-vous avec votre site ? » — si le low-cost n'a rien produit, ré-audit gratuit." },
    ],
  },
  {
    id: "n-signes-referral",
    name: "Signés — Machine à referrals",
    audience: "Clients signés, semaine 1 à 8",
    active: true,
    steps: [
      { id: "ns1", day: 7, channel: "appel", content: "Point onboarding + demander : « Qui, dans votre entourage pro, perd des clients comme vous en perdiez ? » (2 noms datés)." },
      { id: "ns2", day: 30, channel: "email", content: "Premier rapport de résultats chiffré + rappel programme parrainage." },
      { id: "ns3", day: 60, channel: "whatsapp", content: "Partager le win : « Votre site a généré N demandes ce mois-ci » + demander un avis Google." },
    ],
  },
];

export const seedCompetitors: Competitor[] = [
  {
    id: "comp-weblyon",
    name: "WebLyon Express",
    sector: "tous",
    pricing: "49–89 €/mois, template, sans setup",
    strengths: "Prix d'appel très bas, promesse « en ligne en 48h »",
    weaknesses: "Templates identiques, zéro IA, zéro accompagnement, support ticket only, aucun résultat mesuré",
    counter: "Ne jamais se battre sur le prix. Montrer deux sites WebLyon identiques côte à côte, puis NOTRE overlay IA en action. « Moins cher et invisible, ou rentable et vivant ? » Preuve : Paddy's Corner nous recontactera.",
    updatedAt: daysAgo(9),
  },
  {
    id: "comp-freelance",
    name: "Freelances / neveux",
    sector: "tous",
    pricing: "300–800 € one-shot, pas de récurrent",
    strengths: "Relation de confiance existante (famille, ami)",
    weaknesses: "Pas de maintenance, pas de suivi, site mort en 6 mois, aucune obligation de résultat",
    counter: "Jamais attaquer le neveu (couche « Les Autres » de l'oignon). Proposer un comparatif factuel : dernière mise à jour, vitesse, mobile, conversions. Les chiffres critiquent, pas nous.",
    updatedAt: daysAgo(6),
  },
  {
    id: "comp-resa-platforms",
    name: "Plateformes de résa (TheFork etc.)",
    sector: "restaurant",
    pricing: "Commission 2–4 €/couvert + abonnement",
    strengths: "Apport de trafic immédiat, notoriété",
    weaknesses: "Le resto loue SES clients : commissions à vie, data captive, dépendance aux promos -50 %",
    counter: "Pas un remplacement, un rééquilibrage : « Gardez TheFork pour les nouveaux, récupérez vos habitués en direct. Chaque habitué migré = commission économisée à vie. »",
    updatedAt: daysAgo(15),
  },
];

export const seedActivities: Activity[] = [
  { id: "ac1", date: daysAgo(1), kind: "stage", message: "Le Bouchon des Canuts → Red Zone (objection prix ouverte)", prospectId: "p-bouchon" },
  { id: "ac2", date: daysAgo(1), kind: "campagne", message: "Campagne « Restos Lyon » : 3 nouvelles réponses, 1 RDV réservé" },
  { id: "ac3", date: daysAgo(2), kind: "meeting", message: "Audit dépôt réalisé — Ambulances Rhône Assistance", prospectId: "p-ambulances-rhone" },
  { id: "ac4", date: daysAgo(5), kind: "ia", message: "Script généré pour Plomberie Fabre (démo urgences)", prospectId: "p-boulangerie" },
  { id: "ac5", date: daysAgo(9), kind: "perdu", message: "Paddy's Corner perdu vs WebLyon Express — leçon : démo avant prix, toujours", prospectId: "p-paddy" },
  { id: "ac6", date: daysAgo(18), kind: "signe", message: "SIGNÉ ✓ Menuiserie Charbonnier & Fils — 1 200 € + 190 €/mois", prospectId: "p-menuiserie" },
];

export const DEFAULT_BUSINESS_RULES = `1. La décision EST le produit. On vend une décision, pas un site.
2. Émotion d'abord : démo mobile personnalisée AVANT toute mention de prix.
3. Distinction stricte : OBSTACLES (pré-offre) ≠ OBJECTIONS (post-offre / Red Zone).
4. Oignon du Blâme : Circonstances → Les Autres → Soi. On épluche, on n'argumente pas.
5. Toujours chiffrer la Taxe d'Ignorance (€/mois perdus à ne rien faire).
6. Les 3 Croyances à 10/10 avant de demander la signature : le produit fonctionne, tu le soutiens, ça marche POUR LUI.
7. Chaque contact se termine par un next step DATÉ. Sans exception.
8. Conviction du closer 10/10 requise pour signer. La conviction se transfère.
9. Cibles : restaurants, pubs, ambulances, artisans — Lyon et périphérie.
10. Offre : site premium + overlay IA. Setup 1 200–2 400 € + 190–390 €/mois selon secteur.
11. Ne jamais se battre sur le prix face au low-cost : se battre sur la preuve.
12. Un perdu = nurture 90 jours. Un signé = machine à referrals semaine 1.`;
